// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/room.ts";
import * as $1 from "./routes/api/server.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/room/[roomCode].tsx";
import * as $4 from "./routes/tab.tsx";
import * as $$0 from "./islands/Canvas.tsx";
import * as $$1 from "./islands/Chat.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/Form.tsx";
import * as $$4 from "./islands/Socket.tsx";
import * as $$5 from "./islands/Tab.tsx";

const manifest = {
  routes: {
    "./routes/api/room.ts": $0,
    "./routes/api/server.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/room/[roomCode].tsx": $3,
    "./routes/tab.tsx": $4,
  },
  islands: {
    "./islands/Canvas.tsx": $$0,
    "./islands/Chat.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/Form.tsx": $$3,
    "./islands/Socket.tsx": $$4,
    "./islands/Tab.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
